---
# MQTT component
# https://esphome.io/components/mqtt.html
#

substitutions:
  mqtt_host: !secret mqtt_host
  mqtt_user: !secret mqtt_user
  mqtt_password: !secret mqtt_pwd
  mqtt_port: "1883"

mqtt:
  broker: ${mqtt_host}
  username: ${mqtt_user}
  password: ${mqtt_password}
  port: ${mqtt_port}
